require("myconfig.settings")
require("myconfig.plugins")
require("myconfig.mappings")
require("myconfig.utils")
require("myconfig.telescope")
require("myconfig.lsp-config")
require("myconfig.treesitter-config")
require("myconfig.bufferline-config")
require("myconfig.lualine-colorscheme")
require("myconfig.toggleterm")
require("myconfig.brackets")
-- require("myconfig.completion")
